# Makefile for the Himax touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_HIMAX_I2C)   	+= himax_platform.o himax_852xF.o himax_fw_update.o himax_factory_test.o himax_dsm.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_DEBUG)   += himax_debug.o
