#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
