ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += adp1660.o
obj-$(CONFIG_MSMB_CAMERA) += bd7710.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
obj-$(CONFIG_MSMB_CAMERA) += lm3642.o
#/*<DTS2015071103112 w00182304 20150711 begin*/
obj-$(CONFIG_MSMB_CAMERA) += mp3331.o
#/*DTS2015071103112 w00182304 20150711 end>*/
#/* <DTS2016022602753 guochenguang 20160226 begin */
#obj-$(CONFIG_MSMB_CAMERA) += max77819_flash.o
#/* DTS2016022602753 guochenguang 20160226 end> */
