#/* < DTS2014122400303 yuanzhen 20141224 begin */
# Switch Class Driver
obj-$(CONFIG_SWITCH_USB_CLS)	+= switch_usb_class.o
obj-$(CONFIG_SWITCH_FSA9685)	+= switch_fsa9685.o
#/* DTS2014122400303 yuanzhen 20141224 end > */