#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
