#/* < DTS2014122203451 yangzhenxi 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
#/* < DTS2015011603233 houzhipeng 20150119 begin */
obj-$(CONFIG_MSMB_CAMERA) += mini_isp.o
#/* DTS2015011603233 houzhipeng 20150119 end > */
#/* DTS2014122203451 yangzhenxi 20141223 end > */
