#/*< DTS2014112103069 wanglili 20141121 begin */
#
# Makefile for factory info devices
#
obj-$(CONFIG_HUAWEI_FACTORY_INFO) += hw_fac_info.o config_interface.o
#/* DTS2014112103069 wanglili 20141121 end >*/