#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
#/* < DTS2015020400398 yangyang 20150211 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/mini_isp
#/* < DTS2015020400398  yangyang 20150211 end*/
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
