#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += adp1660.o
obj-$(CONFIG_MSMB_CAMERA) += bd7710.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
obj-$(CONFIG_MSMB_CAMERA) += lm3642.o
#DTS2014122607866 zhangbo00166742 20141226 begin
obj-$(CONFIG_MSMB_CAMERA) += lm3646.o
#DTS2014122607866 zhangbo00166742 20141226 end
#/* <DTS2014080900552 chenyuanquan 20140825 begin */
obj-$(CONFIG_MSMB_CAMERA) += max77819_flash.o
#/* DTS2014080900552 chenyuanquan 20140825 end> */
