#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
#/* < DTS2015010900746 yangzhenxi 20150109 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/mini_isp
#/* DTS2015010900746 yangzhenxi 20150109 end > */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
