#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/msm_vb2
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSMB_CAMERA) += msm_vb2.o
