# /*< DTS2015012606635 tangying/205982 20150126 begin*/
# /*add camera ois driver*/
#/* < DTS2014122203451 yangyang 20141223 begin */
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_misp/sensor/ois
#/* DTS2014122203451 yangyang 20141223 end > */
obj-$(CONFIG_MSMB_CAMERA) += imx278_sunny_ois.o
obj-$(CONFIG_MSMB_CAMERA) += imx278_liteon_ois.o
obj-$(CONFIG_MSMB_CAMERA) += imx278_lgit_ois.o
# /*DTS2015012606635 tangying/205982 20150126 end >*/
