obj-$(CONFIG_MSM_VIDC_V4L2) := 	msm_v4l2_vidc.o \
				msm_vidc_common.o \
				msm_vidc.o \
				msm_vdec.o \
				msm_venc.o \
				msm_smem.o \
				msm_vidc_debug.o \
				msm_vidc_res_parse.o \
				venus_hfi.o \
				hfi_response_handler.o \
				hfi_packetization.o \
				vidc_hfi.o \
				q6_hfi.o \
				venus_boot.o

obj-$(CONFIG_MSM_VIDC_VMEM) += vmem/
#/* < DTS2015042906355 y00294389 20150525 begin */
#/* < DTS2014111105636 Houzhipeng hwx231787 20141111 begin */
obj-$(CONFIG_HUAWEI_DSM) += msm_camera_vid_dsm.o \
#/* DTS2014111105636 Houzhipeng hwx231787 20141111 end > */
#/* DTS2015042906355 y00294389 20150525 end > */
