#
# Makefile for the Novatek NT11205 touchscreen driver.
#

# Each configuration option enables a list of files.

obj-y	+= NVTtouch_206.o NVTtouch_206_ext_proc.o NVTtouch_206_fw_update.o NVTtouch_206_mp_ctrlram.o NVTtouch_206_dsm.o
